apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c','mkdir /export/volume/ && touch /export/volume/app.log']
