---
apiVersion: v1
kind: Pod
metadata:
  name: l5d-test-client
  labels:
    app: l5d-test
spec:
  containers:
    - name: server
      image: plavignotte/continuous-curl
      imagePullPolicy: IfNotPresent
      args:
        - "l5d-test-server:8000"
      env:
        - name: DEBUG
          value: "1"
        - name: LOOP
          value: "10" # curl every 10 seconds
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: http_proxy
          ## this really should be going to the node name, but we couldn't use the host network in setting that up
          ## because I wasn't ready to use linkerd as my ingress controller, and didn't actually turn it off (if you can)
          ## Should work fine I just point it at the linkerd service though
          # value: $(NODE_NAME):4140
          value: l5d.linkerd.svc.cluster.local:4140
