apiVersion: v1
kind: PersistentVolume
metadata:
  name: subhash-prometheus-alertmanager
  namespace: ingress-nginx
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.104
    path: "/srv/nfs/kubedata"
