apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subhash-prometheus-alertmanager
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi
