kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-persistent-volumeclaim2
spec:
  storageClassName: pv-demo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
